import '../index.html'
// import '../fonts/scss/font-awesome.scss'
// import './bootstrap.min.js'
import './bg-elements.js'
import './preloader.js'
import './modal.js'
import './scrollToTop.js'
import '../../node_modules/swiper/swiper.scss';
import './slider.js'
import './mainData.js'
// import '../css/style.css'
import '../sass/style.scss'